spring:
  kafka:
    bootstrap-servers: 192.168.1.108:9092,192.168.1.106:9092

    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1
      bootstrap-servers: 192.168.1.106:9092
    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
      bootstrap-servers: 192.168.1.106:9092
kafka:
  topic:
    group-id: topicGroupId5
    topic-name:
      - 192.168.1.106
      - 192.168.1.108
server:
  port: 8081
logging:
  level:
    ROOT: info