server:
  port: 9090
ribbon: #ribbon负载均衡参数配置
  eureka:
      enabled: true
spring:
  application:
    name: consume
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0   # 采样比例设置 1.0 全部获取  0->1
eureka:
  instance:
    hostname: localhost
    statusPageUrl: http://localhost:9090/swagger-ui.html
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
