version: '2'
services:
  message-zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    hostname: 192.168.1.106
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: 192.168.1.106:2888:3888,192.168.1.108:2888:3888
